### ISSUE TITLE
SilverLining - Ruby Developer - Remote/Saigon - C

### ISSUE THREAD

**Issue by son351** [awesome-jobs/vietnam#189]
## Location
- Saigon, Vietnam
- Remote
## Budget
- $500 - $1000 for 1 - 2 weeks
## Requirements
- Familiar with Ruby programming language.
- PostgreSQL.
- Knowledge of Unix/Linux environments.
- Solid understanding of object-oriented programming.
- Understanding of front-end technologies, such as Javascript, HTML5, CSS3.
### Ideally
- Experience with front-end: Bootstrap, CoffeeScript/JavaScript, HTML with HAML, Sass
- Experience API: Grape, Grape entity
- Experience Background job: Sidetiq
- Experience Deploy: Dokku on Ubuntu
### You’ll be responsible for
- Add-in some new features.
- Implement solutions using ruby on rails framework.
- Implement front-end changes based on UX design requirements.
- Implement CSS and javascript changes to achieve requirements. 
### Contact

Nguyễn Hoàng Sơn - 0968 99 88 50 - skype: son_it357 - email: hoangson@silverlining.vn - website: http://silverlining.vn

**Comment by joneslee85** [comment]
Thanks Sơn for this submission. I have few things to weight in:

* What is `Budget`? It seems to be you are likely looking for a Contractor than a Part-Time role. If not, is it meant to be `Salary` instead?
* The `Requirements` section is like a software spec rather than things that you would expect from your potential candidates. From the look of the spec, it seems to me your app is purely API app, so I would like to suggest you put in some time to work out what expectation in regards to that aspect.
* Plus, I am questioning the relevancy about `Building backend using Ruby on Rails` with the `Requirements`
* Do you have any details on this company? Would you be able to provide your email as contact point too ? Please be noted, we _do not_ accept third party recruiter, if you do not work directly with this company, please close it off.

That's all I have. Please review and amend accordingly.

**Comment by son351** [comment]
Thanks @joneslee85 for your comments and please refer back to my resubmit for the JD. Also I'm currently working for this company. If anything is unclear, please advise.

**Comment by joneslee85** [comment]
:+1: looks good, please feel free to amend this post with the details about your company, what sort of products / services
