### ISSUE TITLE
Ruby Yoda - 2 Senior JS Developers - Saigon - FT

### ISSUE THREAD

**Issue by webgago** [awesome-jobs/vietnam#297]
## Location

* Saigon, Vietnam

### Ruby Yoda Vietnam
We are small and young yet. We solve problems of our clients and build own startups.
These positions are for our startup in logistics market (worldwide). 

## Salary Expectation

* $1600/month, negotiable (really depends on your skills)

## Requirements
* Javascript 
* ReactJS
* TDD/BDD, know how to write good specs.
* Know how to test applications
* English proficiency

### Responsibilities
* Build modular, well tested web-client (SPA) from scratch 

### You can bring
* All your knowledge in how to build great products

### Contact

Tony: asozontov at gmail dot com
https://www.facebook.com/rubyyodavietnam

**Comment by huydx** [comment]
@webgago can you add more information about your company?

**Comment by webgago** [comment]
@huydx We are small and young yet. We solve problems of our clients and build own startups.

**Comment by joneslee85** [comment]
@webgago can you please update your description or at least have your public identity like Facebook page or website correctly done? We could not approve a job post that is lacking in details.

**Comment by webgago** [comment]
@joneslee85 updated. thanks for the feedback!

**Comment by joneslee85** [comment]
@webgago I would like to let you know that I decide to close this job post instead because it is still lacking what we consider a good quality post; firstly there is no proper website setup but a dummy one, if your company decide to use FB as homepage, you could redirect the domain to the homepage easily. I just don't feel your firm is a good one if I were a candidate, please excuse me if this offends you in anyway. I am happy to review it again once you up your game. Kind regards
